[build]
publish = "/"
command = "npm run build" # "echo 'Netlify build starting'" ወደ ትክክለኛው ትዕዛዝ መልሰናል

[functions]
directory = "netlify/functions"  # ፋይልዎ የሚገኝበትን ትክክለኛ መንገድ ጠቁም።

[[redirects]]
from = "/.netlify/functions/tbot_handler"
to = "/.netlify/functions/tbot_handler"
status = 200
force = true
