[build]
publish = "/"
command = "echo 'Netlify build starting'"

[functions]
directory = "netlify"
node_version = "18"

[[redirects]]
from = "/.netlify/functions/tbot_handler"
to = "/.netlify/functions/tbot_handler"
status = 200
force = true
